// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZNCYJOWxUOC-73lARl6P85iCQNcvFBaU',
    appId: '1:498711263043:web:50bb4df6f8358c4c3921f6',
    messagingSenderId: '498711263043',
    projectId: 'love-app-4e2ac',
    authDomain: 'love-app-4e2ac.firebaseapp.com',
    storageBucket: 'love-app-4e2ac.firebasestorage.app',
    measurementId: 'G-LEPD680BBR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAviSrA672_F-WDTauYIalD0_H2EXbRnpA',
    appId: '1:498711263043:android:75fce18777a298303921f6',
    messagingSenderId: '498711263043',
    projectId: 'love-app-4e2ac',
    storageBucket: 'love-app-4e2ac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXqm1jEbtDhvgxxtrSOhf9l-f14APwuKA',
    appId: '1:498711263043:ios:d899367b806291ce3921f6',
    messagingSenderId: '498711263043',
    projectId: 'love-app-4e2ac',
    storageBucket: 'love-app-4e2ac.firebasestorage.app',
    iosBundleId: 'com.loveapp.loveApp',
  );
}
